apiVersion: v1
kind: Service
metadata:
  name: logger
spec:
  type: NodePort
  selector:
    app: logger
  ports:
    - name: ui
      port: 8080
      targetPort: 8080
      nodePort: 30080
    - name: ingest
      port: 9000
      targetPort: 9000
      nodePort: 30900 