apiVersion: v1
kind: Service
metadata:
  name: logger
spec:
  type: {{ .Values.service.type }}
  selector:
    app: logger
  ports:
    - name: ui
      port: {{ .Values.service.uiPort }}
      targetPort: {{ .Values.service.uiPort }}
      nodePort: {{ .Values.service.uiNodePort }}
    - name: ingest
      port: {{ .Values.service.ingestPort }}
      targetPort: {{ .Values.service.ingestPort }}
      nodePort: {{ .Values.service.ingestNodePort }} 